// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bin.proto

package u1467085.feedbins;

public interface BinStatusUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:feedbins.BinStatusUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.feedbins.Stuff stuff = 1;</code>
   */
  boolean hasStuff();
  /**
   * <code>.feedbins.Stuff stuff = 1;</code>
   */
  u1467085.feedbins.Stuff getStuff();
  /**
   * <code>.feedbins.Stuff stuff = 1;</code>
   */
  u1467085.feedbins.StuffOrBuilder getStuffOrBuilder();

  /**
   * <code>.feedbins.StuffAmount amount = 2;</code>
   */
  boolean hasAmount();
  /**
   * <code>.feedbins.StuffAmount amount = 2;</code>
   */
  u1467085.feedbins.StuffAmount getAmount();
  /**
   * <code>.feedbins.StuffAmount amount = 2;</code>
   */
  u1467085.feedbins.StuffAmountOrBuilder getAmountOrBuilder();
}
