// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bin.proto

package u1467085.feedbins;

public interface ChatMessageFromServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:feedbins.ChatMessageFromServer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.feedbins.ChatMessage message = 1;</code>
   */
  boolean hasMessage();
  /**
   * <code>.feedbins.ChatMessage message = 1;</code>
   */
  u1467085.feedbins.ChatMessage getMessage();
  /**
   * <code>.feedbins.ChatMessage message = 1;</code>
   */
  u1467085.feedbins.ChatMessageOrBuilder getMessageOrBuilder();
}
