// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bin.proto

package u1467085.feedbins;

public interface OperationStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:feedbins.OperationStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.feedbins.OperationStatusResponse.OperationStatus result = 1;</code>
   */
  int getResultValue();
  /**
   * <code>.feedbins.OperationStatusResponse.OperationStatus result = 1;</code>
   */
  u1467085.feedbins.OperationStatusResponse.OperationStatus getResult();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
