// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bin.proto

package u1467085.feedbins;

public interface StuffOrBuilder extends
    // @@protoc_insertion_point(interface_extends:feedbins.Stuff)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string stuffName = 1;</code>
   */
  java.lang.String getStuffName();
  /**
   * <code>string stuffName = 1;</code>
   */
  com.google.protobuf.ByteString
      getStuffNameBytes();
}
