// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bin.proto

package u1467085.feedbins;

public interface StuffAmountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:feedbins.StuffAmount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 stuffAmount = 1;</code>
   */
  int getStuffAmount();
}
