// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package u1467085.feedbincontroller;

public interface BinIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:feedbins.BinId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();
}
