// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package u1467085.feedbincontroller;

/**
 * Protobuf type {@code feedbins.BinRecord}
 */
public  final class BinRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:feedbins.BinRecord)
    BinRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BinRecord.newBuilder() to construct.
  private BinRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BinRecord() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BinRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            u1467085.feedbincontroller.ProductionLine.Builder subBuilder = null;
            if (line_ != null) {
              subBuilder = line_.toBuilder();
            }
            line_ = input.readMessage(u1467085.feedbincontroller.ProductionLine.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(line_);
              line_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            u1467085.feedbincontroller.BinId.Builder subBuilder = null;
            if (binId_ != null) {
              subBuilder = binId_.toBuilder();
            }
            binId_ = input.readMessage(u1467085.feedbincontroller.BinId.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(binId_);
              binId_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return u1467085.feedbincontroller.FeedBinController.internal_static_feedbins_BinRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return u1467085.feedbincontroller.FeedBinController.internal_static_feedbins_BinRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            u1467085.feedbincontroller.BinRecord.class, u1467085.feedbincontroller.BinRecord.Builder.class);
  }

  public static final int LINE_FIELD_NUMBER = 1;
  private u1467085.feedbincontroller.ProductionLine line_;
  /**
   * <code>.feedbins.ProductionLine line = 1;</code>
   */
  public boolean hasLine() {
    return line_ != null;
  }
  /**
   * <code>.feedbins.ProductionLine line = 1;</code>
   */
  public u1467085.feedbincontroller.ProductionLine getLine() {
    return line_ == null ? u1467085.feedbincontroller.ProductionLine.getDefaultInstance() : line_;
  }
  /**
   * <code>.feedbins.ProductionLine line = 1;</code>
   */
  public u1467085.feedbincontroller.ProductionLineOrBuilder getLineOrBuilder() {
    return getLine();
  }

  public static final int BINID_FIELD_NUMBER = 2;
  private u1467085.feedbincontroller.BinId binId_;
  /**
   * <code>.feedbins.BinId binId = 2;</code>
   */
  public boolean hasBinId() {
    return binId_ != null;
  }
  /**
   * <code>.feedbins.BinId binId = 2;</code>
   */
  public u1467085.feedbincontroller.BinId getBinId() {
    return binId_ == null ? u1467085.feedbincontroller.BinId.getDefaultInstance() : binId_;
  }
  /**
   * <code>.feedbins.BinId binId = 2;</code>
   */
  public u1467085.feedbincontroller.BinIdOrBuilder getBinIdOrBuilder() {
    return getBinId();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (line_ != null) {
      output.writeMessage(1, getLine());
    }
    if (binId_ != null) {
      output.writeMessage(2, getBinId());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (line_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLine());
    }
    if (binId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBinId());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof u1467085.feedbincontroller.BinRecord)) {
      return super.equals(obj);
    }
    u1467085.feedbincontroller.BinRecord other = (u1467085.feedbincontroller.BinRecord) obj;

    if (hasLine() != other.hasLine()) return false;
    if (hasLine()) {
      if (!getLine()
          .equals(other.getLine())) return false;
    }
    if (hasBinId() != other.hasBinId()) return false;
    if (hasBinId()) {
      if (!getBinId()
          .equals(other.getBinId())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLine()) {
      hash = (37 * hash) + LINE_FIELD_NUMBER;
      hash = (53 * hash) + getLine().hashCode();
    }
    if (hasBinId()) {
      hash = (37 * hash) + BINID_FIELD_NUMBER;
      hash = (53 * hash) + getBinId().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static u1467085.feedbincontroller.BinRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static u1467085.feedbincontroller.BinRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static u1467085.feedbincontroller.BinRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static u1467085.feedbincontroller.BinRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static u1467085.feedbincontroller.BinRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static u1467085.feedbincontroller.BinRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static u1467085.feedbincontroller.BinRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static u1467085.feedbincontroller.BinRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static u1467085.feedbincontroller.BinRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static u1467085.feedbincontroller.BinRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static u1467085.feedbincontroller.BinRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static u1467085.feedbincontroller.BinRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(u1467085.feedbincontroller.BinRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code feedbins.BinRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:feedbins.BinRecord)
      u1467085.feedbincontroller.BinRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return u1467085.feedbincontroller.FeedBinController.internal_static_feedbins_BinRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return u1467085.feedbincontroller.FeedBinController.internal_static_feedbins_BinRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              u1467085.feedbincontroller.BinRecord.class, u1467085.feedbincontroller.BinRecord.Builder.class);
    }

    // Construct using u1467085.feedbincontroller.BinRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (lineBuilder_ == null) {
        line_ = null;
      } else {
        line_ = null;
        lineBuilder_ = null;
      }
      if (binIdBuilder_ == null) {
        binId_ = null;
      } else {
        binId_ = null;
        binIdBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return u1467085.feedbincontroller.FeedBinController.internal_static_feedbins_BinRecord_descriptor;
    }

    @java.lang.Override
    public u1467085.feedbincontroller.BinRecord getDefaultInstanceForType() {
      return u1467085.feedbincontroller.BinRecord.getDefaultInstance();
    }

    @java.lang.Override
    public u1467085.feedbincontroller.BinRecord build() {
      u1467085.feedbincontroller.BinRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public u1467085.feedbincontroller.BinRecord buildPartial() {
      u1467085.feedbincontroller.BinRecord result = new u1467085.feedbincontroller.BinRecord(this);
      if (lineBuilder_ == null) {
        result.line_ = line_;
      } else {
        result.line_ = lineBuilder_.build();
      }
      if (binIdBuilder_ == null) {
        result.binId_ = binId_;
      } else {
        result.binId_ = binIdBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof u1467085.feedbincontroller.BinRecord) {
        return mergeFrom((u1467085.feedbincontroller.BinRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(u1467085.feedbincontroller.BinRecord other) {
      if (other == u1467085.feedbincontroller.BinRecord.getDefaultInstance()) return this;
      if (other.hasLine()) {
        mergeLine(other.getLine());
      }
      if (other.hasBinId()) {
        mergeBinId(other.getBinId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      u1467085.feedbincontroller.BinRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (u1467085.feedbincontroller.BinRecord) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private u1467085.feedbincontroller.ProductionLine line_;
    private com.google.protobuf.SingleFieldBuilderV3<
        u1467085.feedbincontroller.ProductionLine, u1467085.feedbincontroller.ProductionLine.Builder, u1467085.feedbincontroller.ProductionLineOrBuilder> lineBuilder_;
    /**
     * <code>.feedbins.ProductionLine line = 1;</code>
     */
    public boolean hasLine() {
      return lineBuilder_ != null || line_ != null;
    }
    /**
     * <code>.feedbins.ProductionLine line = 1;</code>
     */
    public u1467085.feedbincontroller.ProductionLine getLine() {
      if (lineBuilder_ == null) {
        return line_ == null ? u1467085.feedbincontroller.ProductionLine.getDefaultInstance() : line_;
      } else {
        return lineBuilder_.getMessage();
      }
    }
    /**
     * <code>.feedbins.ProductionLine line = 1;</code>
     */
    public Builder setLine(u1467085.feedbincontroller.ProductionLine value) {
      if (lineBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        line_ = value;
        onChanged();
      } else {
        lineBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.feedbins.ProductionLine line = 1;</code>
     */
    public Builder setLine(
        u1467085.feedbincontroller.ProductionLine.Builder builderForValue) {
      if (lineBuilder_ == null) {
        line_ = builderForValue.build();
        onChanged();
      } else {
        lineBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.feedbins.ProductionLine line = 1;</code>
     */
    public Builder mergeLine(u1467085.feedbincontroller.ProductionLine value) {
      if (lineBuilder_ == null) {
        if (line_ != null) {
          line_ =
            u1467085.feedbincontroller.ProductionLine.newBuilder(line_).mergeFrom(value).buildPartial();
        } else {
          line_ = value;
        }
        onChanged();
      } else {
        lineBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.feedbins.ProductionLine line = 1;</code>
     */
    public Builder clearLine() {
      if (lineBuilder_ == null) {
        line_ = null;
        onChanged();
      } else {
        line_ = null;
        lineBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.feedbins.ProductionLine line = 1;</code>
     */
    public u1467085.feedbincontroller.ProductionLine.Builder getLineBuilder() {
      
      onChanged();
      return getLineFieldBuilder().getBuilder();
    }
    /**
     * <code>.feedbins.ProductionLine line = 1;</code>
     */
    public u1467085.feedbincontroller.ProductionLineOrBuilder getLineOrBuilder() {
      if (lineBuilder_ != null) {
        return lineBuilder_.getMessageOrBuilder();
      } else {
        return line_ == null ?
            u1467085.feedbincontroller.ProductionLine.getDefaultInstance() : line_;
      }
    }
    /**
     * <code>.feedbins.ProductionLine line = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        u1467085.feedbincontroller.ProductionLine, u1467085.feedbincontroller.ProductionLine.Builder, u1467085.feedbincontroller.ProductionLineOrBuilder> 
        getLineFieldBuilder() {
      if (lineBuilder_ == null) {
        lineBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            u1467085.feedbincontroller.ProductionLine, u1467085.feedbincontroller.ProductionLine.Builder, u1467085.feedbincontroller.ProductionLineOrBuilder>(
                getLine(),
                getParentForChildren(),
                isClean());
        line_ = null;
      }
      return lineBuilder_;
    }

    private u1467085.feedbincontroller.BinId binId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        u1467085.feedbincontroller.BinId, u1467085.feedbincontroller.BinId.Builder, u1467085.feedbincontroller.BinIdOrBuilder> binIdBuilder_;
    /**
     * <code>.feedbins.BinId binId = 2;</code>
     */
    public boolean hasBinId() {
      return binIdBuilder_ != null || binId_ != null;
    }
    /**
     * <code>.feedbins.BinId binId = 2;</code>
     */
    public u1467085.feedbincontroller.BinId getBinId() {
      if (binIdBuilder_ == null) {
        return binId_ == null ? u1467085.feedbincontroller.BinId.getDefaultInstance() : binId_;
      } else {
        return binIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.feedbins.BinId binId = 2;</code>
     */
    public Builder setBinId(u1467085.feedbincontroller.BinId value) {
      if (binIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        binId_ = value;
        onChanged();
      } else {
        binIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.feedbins.BinId binId = 2;</code>
     */
    public Builder setBinId(
        u1467085.feedbincontroller.BinId.Builder builderForValue) {
      if (binIdBuilder_ == null) {
        binId_ = builderForValue.build();
        onChanged();
      } else {
        binIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.feedbins.BinId binId = 2;</code>
     */
    public Builder mergeBinId(u1467085.feedbincontroller.BinId value) {
      if (binIdBuilder_ == null) {
        if (binId_ != null) {
          binId_ =
            u1467085.feedbincontroller.BinId.newBuilder(binId_).mergeFrom(value).buildPartial();
        } else {
          binId_ = value;
        }
        onChanged();
      } else {
        binIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.feedbins.BinId binId = 2;</code>
     */
    public Builder clearBinId() {
      if (binIdBuilder_ == null) {
        binId_ = null;
        onChanged();
      } else {
        binId_ = null;
        binIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.feedbins.BinId binId = 2;</code>
     */
    public u1467085.feedbincontroller.BinId.Builder getBinIdBuilder() {
      
      onChanged();
      return getBinIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.feedbins.BinId binId = 2;</code>
     */
    public u1467085.feedbincontroller.BinIdOrBuilder getBinIdOrBuilder() {
      if (binIdBuilder_ != null) {
        return binIdBuilder_.getMessageOrBuilder();
      } else {
        return binId_ == null ?
            u1467085.feedbincontroller.BinId.getDefaultInstance() : binId_;
      }
    }
    /**
     * <code>.feedbins.BinId binId = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        u1467085.feedbincontroller.BinId, u1467085.feedbincontroller.BinId.Builder, u1467085.feedbincontroller.BinIdOrBuilder> 
        getBinIdFieldBuilder() {
      if (binIdBuilder_ == null) {
        binIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            u1467085.feedbincontroller.BinId, u1467085.feedbincontroller.BinId.Builder, u1467085.feedbincontroller.BinIdOrBuilder>(
                getBinId(),
                getParentForChildren(),
                isClean());
        binId_ = null;
      }
      return binIdBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:feedbins.BinRecord)
  }

  // @@protoc_insertion_point(class_scope:feedbins.BinRecord)
  private static final u1467085.feedbincontroller.BinRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new u1467085.feedbincontroller.BinRecord();
  }

  public static u1467085.feedbincontroller.BinRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BinRecord>
      PARSER = new com.google.protobuf.AbstractParser<BinRecord>() {
    @java.lang.Override
    public BinRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BinRecord(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BinRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BinRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public u1467085.feedbincontroller.BinRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

