// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package u1467085.feedbincontroller;

public interface BinRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:feedbins.BinRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.feedbins.ProductionLine line = 1;</code>
   */
  boolean hasLine();
  /**
   * <code>.feedbins.ProductionLine line = 1;</code>
   */
  u1467085.feedbincontroller.ProductionLine getLine();
  /**
   * <code>.feedbins.ProductionLine line = 1;</code>
   */
  u1467085.feedbincontroller.ProductionLineOrBuilder getLineOrBuilder();

  /**
   * <code>.feedbins.BinId binId = 2;</code>
   */
  boolean hasBinId();
  /**
   * <code>.feedbins.BinId binId = 2;</code>
   */
  u1467085.feedbincontroller.BinId getBinId();
  /**
   * <code>.feedbins.BinId binId = 2;</code>
   */
  u1467085.feedbincontroller.BinIdOrBuilder getBinIdOrBuilder();
}
