// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package u1467085.feedbincontroller;

public interface ChangeBinStuffOrBuilder extends
    // @@protoc_insertion_point(interface_extends:feedbins.ChangeBinStuff)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.feedbins.BinId id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>.feedbins.BinId id = 1;</code>
   */
  u1467085.feedbincontroller.BinId getId();
  /**
   * <code>.feedbins.BinId id = 1;</code>
   */
  u1467085.feedbincontroller.BinIdOrBuilder getIdOrBuilder();

  /**
   * <code>.feedbins.Stuff stuff = 2;</code>
   */
  boolean hasStuff();
  /**
   * <code>.feedbins.Stuff stuff = 2;</code>
   */
  u1467085.feedbincontroller.Stuff getStuff();
  /**
   * <code>.feedbins.Stuff stuff = 2;</code>
   */
  u1467085.feedbincontroller.StuffOrBuilder getStuffOrBuilder();
}
