// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package u1467085.feedbincontroller;

public final class FeedBinController {
  private FeedBinController() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_OperationStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_OperationStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_BinId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_BinId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_Stuff_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_Stuff_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_ProductionLine_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_ProductionLine_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_BinStatusUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_BinStatusUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_BinRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_BinRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_FillBin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_FillBin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_ChangeBinStuff_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_ChangeBinStuff_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020controller.proto\022\010feedbins\032\033google/pro" +
      "tobuf/empty.proto\"\227\001\n\027OperationStatusRes" +
      "ponse\022A\n\006result\030\001 \001(\01621.feedbins.Operati" +
      "onStatusResponse.OperationStatus\022\017\n\007mess" +
      "age\030\002 \001(\t\"(\n\017OperationStatus\022\013\n\007SUCCESS\020" +
      "\000\022\010\n\004FAIL\020\001\"&\n\005BinId\022\017\n\007address\030\001 \001(\t\022\014\n" +
      "\004port\030\002 \001(\005\"\032\n\005Stuff\022\021\n\tstuffName\030\001 \001(\t\"" +
      "\036\n\016ProductionLine\022\014\n\004name\030\001 \001(\t\"y\n\017BinSt" +
      "atusUpdate\022#\n\006record\030\001 \001(\0132\023.feedbins.Bi" +
      "nRecord\022\036\n\005stuff\030\002 \001(\0132\017.feedbins.Stuff\022" +
      "\016\n\006amount\030\003 \001(\005\022\021\n\tmaxAmount\030\004 \001(\005\"S\n\tBi" +
      "nRecord\022&\n\004line\030\001 \001(\0132\030.feedbins.Product" +
      "ionLine\022\036\n\005binId\030\002 \001(\0132\017.feedbins.BinId\"" +
      "6\n\007FillBin\022\033\n\002id\030\001 \001(\0132\017.feedbins.BinId\022" +
      "\016\n\006amount\030\002 \001(\005\"M\n\016ChangeBinStuff\022\033\n\002id\030" +
      "\001 \001(\0132\017.feedbins.BinId\022\036\n\005stuff\030\002 \001(\0132\017." +
      "feedbins.Stuff2\204\004\n\030FeedBinControllerServ" +
      "ice\022I\n\022registerForUpdates\022\026.google.proto" +
      "buf.Empty\032\031.feedbins.BinStatusUpdate0\001\022@" +
      "\n\006addBin\022\023.feedbins.BinRecord\032!.feedbins" +
      ".OperationStatusResponse\022S\n\024createProduc" +
      "tionLine\022\030.feedbins.ProductionLine\032!.fee" +
      "dbins.OperationStatusResponse\022>\n\010flushBi" +
      "n\022\017.feedbins.BinId\032!.feedbins.OperationS" +
      "tatusResponse\0228\n\ninspectBin\022\017.feedbins.B" +
      "inId\032\031.feedbins.BinStatusUpdate\022@\n\010addSt" +
      "uff\022\021.feedbins.FillBin\032!.feedbins.Operat" +
      "ionStatusResponse\022J\n\013changeStuff\022\030.feedb" +
      "ins.ChangeBinStuff\032!.feedbins.OperationS" +
      "tatusResponseB6\n\032u1467085.feedbincontrol" +
      "lerB\021FeedBinControllerP\001\242\002\002FBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_feedbins_OperationStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_feedbins_OperationStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_OperationStatusResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
    internal_static_feedbins_BinId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_feedbins_BinId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_BinId_descriptor,
        new java.lang.String[] { "Address", "Port", });
    internal_static_feedbins_Stuff_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_feedbins_Stuff_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_Stuff_descriptor,
        new java.lang.String[] { "StuffName", });
    internal_static_feedbins_ProductionLine_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_feedbins_ProductionLine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_ProductionLine_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_feedbins_BinStatusUpdate_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_feedbins_BinStatusUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_BinStatusUpdate_descriptor,
        new java.lang.String[] { "Record", "Stuff", "Amount", "MaxAmount", });
    internal_static_feedbins_BinRecord_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_feedbins_BinRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_BinRecord_descriptor,
        new java.lang.String[] { "Line", "BinId", });
    internal_static_feedbins_FillBin_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_feedbins_FillBin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_FillBin_descriptor,
        new java.lang.String[] { "Id", "Amount", });
    internal_static_feedbins_ChangeBinStuff_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_feedbins_ChangeBinStuff_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_ChangeBinStuff_descriptor,
        new java.lang.String[] { "Id", "Stuff", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
