// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package u1467085.feedbincontroller;

public final class FeedBinController {
  private FeedBinController() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_OperationStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_OperationStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_BinId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_BinId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_Stuff_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_Stuff_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_ControllerBinStatusUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_ControllerBinStatusUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_FillBin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_FillBin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedbins_ChangeBinStuff_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedbins_ChangeBinStuff_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020controller.proto\022\010feedbins\032\033google/pro" +
      "tobuf/empty.proto\"\227\001\n\027OperationStatusRes" +
      "ponse\022A\n\006result\030\001 \001(\01621.feedbins.Operati" +
      "onStatusResponse.OperationStatus\022\017\n\007mess" +
      "age\030\002 \001(\t\"(\n\017OperationStatus\022\013\n\007SUCCESS\020" +
      "\000\022\010\n\004FAIL\020\001\"&\n\005BinId\022\017\n\007address\030\001 \001(\t\022\014\n" +
      "\004port\030\002 \001(\005\"\032\n\005Stuff\022\021\n\tstuffName\030\001 \001(\t\"" +
      "\177\n\031ControllerBinStatusUpdate\022\037\n\006record\030\001" +
      " \001(\0132\017.feedbins.BinId\022\036\n\005stuff\030\002 \001(\0132\017.f" +
      "eedbins.Stuff\022\016\n\006amount\030\003 \001(\005\022\021\n\tmaxAmou" +
      "nt\030\004 \001(\005\"6\n\007FillBin\022\033\n\002id\030\001 \001(\0132\017.feedbi" +
      "ns.BinId\022\016\n\006amount\030\002 \001(\005\"M\n\016ChangeBinStu" +
      "ff\022\033\n\002id\030\001 \001(\0132\017.feedbins.BinId\022\036\n\005stuff" +
      "\030\002 \001(\0132\017.feedbins.Stuff2\302\003\n\030FeedBinContr" +
      "ollerService\022V\n\025registerForBinUpdates\022\026." +
      "google.protobuf.Empty\032#.feedbins.Control" +
      "lerBinStatusUpdate0\001\022<\n\006addBin\022\017.feedbin" +
      "s.BinId\032!.feedbins.OperationStatusRespon" +
      "se\022>\n\010flushBin\022\017.feedbins.BinId\032!.feedbi" +
      "ns.OperationStatusResponse\022B\n\ninspectBin" +
      "\022\017.feedbins.BinId\032#.feedbins.ControllerB" +
      "inStatusUpdate\022@\n\010addStuff\022\021.feedbins.Fi" +
      "llBin\032!.feedbins.OperationStatusResponse" +
      "\022J\n\013changeStuff\022\030.feedbins.ChangeBinStuf" +
      "f\032!.feedbins.OperationStatusResponseB6\n\032" +
      "u1467085.feedbincontrollerB\021FeedBinContr" +
      "ollerP\001\242\002\002FBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_feedbins_OperationStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_feedbins_OperationStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_OperationStatusResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
    internal_static_feedbins_BinId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_feedbins_BinId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_BinId_descriptor,
        new java.lang.String[] { "Address", "Port", });
    internal_static_feedbins_Stuff_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_feedbins_Stuff_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_Stuff_descriptor,
        new java.lang.String[] { "StuffName", });
    internal_static_feedbins_ControllerBinStatusUpdate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_feedbins_ControllerBinStatusUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_ControllerBinStatusUpdate_descriptor,
        new java.lang.String[] { "Record", "Stuff", "Amount", "MaxAmount", });
    internal_static_feedbins_FillBin_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_feedbins_FillBin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_FillBin_descriptor,
        new java.lang.String[] { "Id", "Amount", });
    internal_static_feedbins_ChangeBinStuff_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_feedbins_ChangeBinStuff_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedbins_ChangeBinStuff_descriptor,
        new java.lang.String[] { "Id", "Stuff", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
