// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller.proto

package u1467085.feedbincontroller;

public interface FillBinOrBuilder extends
    // @@protoc_insertion_point(interface_extends:feedbins.FillBin)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.feedbins.BinId id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>.feedbins.BinId id = 1;</code>
   */
  u1467085.feedbincontroller.BinId getId();
  /**
   * <code>.feedbins.BinId id = 1;</code>
   */
  u1467085.feedbincontroller.BinIdOrBuilder getIdOrBuilder();

  /**
   * <code>int32 amount = 2;</code>
   */
  int getAmount();
}
